# fly.toml app configuration file generated for brit-insurance on 2023-12-16T17:56:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brit-insurance"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  PRIMARY_REGION = "lhr"
  DATABASE_FILE = "/storage/database.json"

[[mounts]]
  source = "brit_storage"
  destination = "/storage"
  processes = ["app"]
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          Access-Control-Allow-Headers = "*"
          Access-Control-Allow-Methods = "*"
          Access-Control-Allow-Origin = "*"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
